// trustdonation: drei Sprachen, Aufklapp-Menues, Hell/Dunkel.
// Jeder Text auf den Seiten traegt data-t="schluessel"; hier liegt das Woerterbuch.
var T = {
  "de": {
    "meta.title": "trustdonation — Dein Projekt findet die Stiftungen, die passen.",
    "meta.desc": "280 deutsche Stiftungen auf einer Karte. Trag dein Projekt ein und sieh sofort, welche Stiftungen zu deinen Themen passen. Kostenlos, offener Quellcode.",
    "meta.title.kreislauf": "trustdonation — So läuft es",
    "meta.desc.kreislauf": "Anstifter starten, Zustifter geben, Stiftungen fördern, Projekte arbeiten draußen. Und alle sehen, was daraus wurde.",
    "aria.schema": "Hell oder dunkel",
    "aria.menue": "Menü öffnen oder schließen",
    "nav.fuerwen": "Für wen",
    "nav.projekte": "Projekte",
    "nav.projekte.s": "Trag dein Projekt ein und sieh, welche Stiftungen zu dir passen.",
    "nav.stiftungen": "Stiftungen",
    "nav.stiftungen.s": "Finde Projekte in deinem Feld und bekomm deinen eigenen Raum.",
    "nav.kreislauf": "Kreislauf",
    "nav.ressourcen": "Ressourcen",
    "nav.raum": "Der Raum",
    "nav.karte": "Karte",
    "nav.karte.s": "Alle Stiftungen und Projekte auf einer Karte, direkt in der App.",
    "nav.rubriken": "Förderkriterien",
    "nav.rubriken.s": "Die elf Felder, nach denen Stiftungen fördern.",
    "nav.antragswege": "Antragswege",
    "nav.antragswege.s": "Offen, Wettbewerb, Anfrage, Partnerschaft, Boden.",
    "nav.matching": "Wie alles zusammenfindet",
    "nav.matching.s": "Projekte, Stiftungen und Menschen finden über Themen, Region und Weg zueinander.",
    "nav.offen": "Offen",
    "nav.quellcode": "Real Life Stack",
    "nav.quellcode.s": "Der offene Quellcode auf GitHub.",
    "nav.instanz": "Eigene Instanz",
    "nav.instanz.s": "Eigene Domain, fertiges Image, nur Konfiguration.",
    "nav.android": "Android-App",
    "nav.android.s": "APK, 6 MB, direkt aufs Telefon.",
    "nav.ueber": "Real Life Network",
    "nav.ueber.s": "Das Netzwerk hinter trustdonation.",
    "nav.mitmachen": "Mitmachen",
    "nav.sprache": "Sprache",
    "nav.stil": "Sprachstil",
    "nav.stil.hinweis": "Sprachstile gibt es bisher auf Deutsch.",
    "nav.mehr": "Mehr",
    "nav.app": "App öffnen",
    "cta.app": "App öffnen →",
    "hero.eyebrow": "280 Stiftungen, vier Rollen, eine Karte",
    "hero.h1": "Dein Projekt findet die Stiftungen, die passen.",
    "hero.lede": "trustdonation ist eine Karte. Projekte tragen drei bis sechs Themen ein und sehen sofort, welche von 280 recherchierten Stiftungen dazu passen. Stiftungen sehen, wer in ihrem Feld schon arbeitet. Und wer gibt, sieht später, was daraus geworden ist.",
    "hero.link": "So läuft es",
    "hero.note": "Getragen vom Kollektiv Lichtung e.V. Deine Identität liegt auf deinem Gerät, nicht bei uns.",
    "frame.open": "Karte in der App öffnen →",
    "frame.stiftungen": "Stiftungen",
    "frame.projekte": "Projekte",
    "proof": "<strong>280 deutsche Stiftungen</strong> haben wir durchgesehen und nach elf Förderkriterien sortiert.",
    "r.kicker": "Für wen",
    "r.h2": "Vier Rollen, vier Einstiege.",
    "r.lede": "Vier Rollen, neun Suchen, eine Karte. Anstifter fangen an, Zustifter geben dazu, Stiftungen fördern, Projekte arbeiten draußen. Heute läuft fast jede dieser Suchen über Zufall.",
    "ra.verb": "Anstiften",
    "ra.h3": "Anstifter: du fängst an.",
    "ra.p": "Du startest ein Projekt, bringst deine Begabung ein oder arbeitest in einer Stiftung mit. Zeit, Wissen, Werkzeug, ein Raum: alles zählt. Und wer schon einmal einen Förderantrag geschrieben hat, bringt dem nächsten Projekt genau das bei.",
    "ra.link": "Anstiften →",
    "ra.a": "Werkstatt am Bahnhof",
    "ra.as": "Drei Menschen, ein Raum, ein Anfang",
    "ra.at": "gegründet",
    "ra.b": "Jonas bringt sein Schweißgerät",
    "ra.bs": "Werkstatt am Bahnhof",
    "ra.bt": "Begabung",
    "ra.c": "Lena im Stiftungsrat",
    "ra.cs": "Bürgerstiftung Kassel, seit zwei Jahren",
    "ra.ct": "Nachwuchs",
    "ra.note": "Wer sich trifft, bestätigt sich gegenseitig. Die Bestätigung steht danach im Profil.",
    "rz.verb": "Zustiften",
    "rz.h3": "Zustifter: du gibst dazu.",
    "rz.p": "Du gibst Geld in eine bestehende Stiftung oder direkt an ein Projekt. Beide Wege stehen offen. Was du gibst, bleibt sichtbar: wohin es ging und was daraus wurde. Vertrauen entsteht aus dem, was man nachsehen kann.",
    "rz.link": "Zustiften →",
    "rz.a": "Zustiftung",
    "rz.as": "Stiftung Bildung · Förderfonds Handwerk",
    "rz.at": "5.000 EUR",
    "rz.b": "Direkte Förderung",
    "rz.bs": "Musterschule Gudensberg · Außengelände",
    "rz.bt": "sichtbar",
    "rz.c": "Anna gibt jeden Monat",
    "rz.cs": "Werkstatt am Bahnhof, 50 EUR",
    "rz.ct": "regelmäßig",
    "rz.note": "Jede Gabe wird von beiden Seiten bestätigt und steht dann auf der Karte.",
    "rs.verb": "Finden",
    "rs.h3": "Stiftungen: finde Projekte, die zu deinem Zweck passen.",
    "rs.p": "Trag deinen Förderzweck als Tags ein, dazu Region und Antragsweg. Die Karte zeigt dir, wer in deinem Feld arbeitet, bevor der erste Antrag kommt. Das spart die halbe Stunde für jeden Antrag, der ohnehin nicht passt. Und du bekommst deinen eigenen Raum mit Karte, Community und Quests.",
    "rs.link": "Stiftung eintragen →",
    "rs.a": "Bürgerstiftung Kassel",
    "rs.as": "offen · bis 5.000 EUR · Online-Formular",
    "rs.at": "offen",
    "rs.b": "Software AG-Stiftung, Darmstadt",
    "rs.bs": "zweistufig · 20.000 bis 500.000 EUR",
    "rs.bt": "zweistufig",
    "rs.c": "Edith Maryon Stiftung, Basel",
    "rs.cs": "kauft Boden, verpachtet dauerhaft",
    "rs.ct": "Boden",
    "rs.note": "Jeder Eintrag zeigt Quelle und Prüfdatum. Stiftungen pflegen ihr Profil selbst.",
    "rp.verb": "Zeigen",
    "rp.h3": "Projekte: zeig, woran du arbeitest.",
    "rp.p": "Setz einen Pin auf die Karte, wähl drei bis sechs Themen und deine Region. Aus 280 recherchierten Stiftungen entsteht deine Liste, sortiert nach Übereinstimmung und Nähe. Kein Antragspoker, ein Profil.",
    "rp.link": "Projekt anlegen →",
    "rp.a": "Werkstatt am Bahnhof",
    "rp.as": "#handwerk #jugend #hessen",
    "rp.at": "4 passen",
    "rp.b": "Musterschule Gudensberg",
    "rp.bs": "#bildung #potenzialentfaltung #reformpaedagogik",
    "rp.bt": "9 passen",
    "rp.c": "Vollmondfeuer Lohre",
    "rp.cs": "#gemeinwesen #frieden #innere-arbeit",
    "rp.ct": "3 passen",
    "rp.note": "Sortiert nach gemeinsamen Themen, Region und Größenordnung. Jede Zeile zeigt, warum.",
    "k.kicker": "Der Kreislauf",
    "k.h2": "Ein Kreislauf, kein Antrag.",
    "k.lede": "In der Mitte steht das Vertrauen: das Real Life Trust Protokoll, darum Profile, Karte und Stack. Außen die vier Rollen. Anstifter fangen an, Zustifter geben, Stiftungen fördern, Projekte arbeiten draußen. Was daraus wird, sehen alle, und die nächste Gabe folgt.",
    "d.kern": "Vertrauen",
    "d.kern.sub": "Trust Protokoll",
    "d.profile": "Profile",
    "d.karte": "Karte",
    "d.stack": "Stack",
    "d.anstifter": "Anstifter",
    "d.anstifter.sub": "Menschen",
    "d.zustifter": "Zustifter",
    "d.zustifter.sub": "Gaben",
    "d.stiftungen": "Stiftungen",
    "d.stiftungen.sub": "Kapital",
    "d.projekte": "Projekte",
    "d.projekte.sub": "im Real Life",
    "d.l1": "wachsen hinein",
    "d.l2": "gründen, tragen",
    "d.l3": "stiften zu",
    "d.l4": "fördern direkt",
    "d.l5": "fördern",
    "d.l6": "Wirkung kehrt zurück",
    "k.link": "So läuft es im Ganzen →",
    "band.big": "Ein Topf,<br><em>viele Räume.</em>",
    "band.p": "Jede Stiftung bekommt ihren eigenen Raum: Karte, Community, Quests. Alle zahlen in einen gemeinsamen Topf, der Betrieb, Entwicklung und Verein finanziert. So wächst deine Community, und das Ganze trägt sich selbst.",
    "fact1": "Stiftungen recherchiert",
    "fact2": "Antragswege",
    "fact3": "Förderkriterien",
    "ru.kicker": "Förderkriterien",
    "ru.h2": "Elf Felder, in denen gefördert wird.",
    "ru.lede": "Jedes Projekt und jede Stiftung ordnet sich hier ein. Wo sich die Felder überlappen, finden beide zueinander.",
    "ru1": "Soziale Innovation und Gemeinwohl",
    "ru2": "Digitale Souveränität und Open Source",
    "ru3": "Politische Bildung und Demokratie",
    "ru4": "Kultur und Kunst",
    "ru5": "Handwerk und Berufsorientierung",
    "ru6": "Kinder, Jugend und Familie",
    "ru7": "Gesundheit und Prävention",
    "ru8": "Ländliche Entwicklung und Region",
    "ru9": "Nachhaltigkeit und Kreislaufwirtschaft",
    "ru10": "Frieden und Verständigung",
    "ru11": "Bildung und freie Lernräume",
    "a.kicker": "Ressourcen",
    "a.h2": "Wie du an eine Stiftung herankommst.",
    "a.lede": "Stiftungen bringen Zweck, Kapital, Netzwerk und Wissen mit. Der Weg hinein ist bei jeder anders. Acht Wege unterscheiden wir auf der Karte.",
    "a1.h": "Offen",
    "a1.p": "Offen ausgeschrieben. Jeder gemeinnützige Träger kann einen Antrag stellen. Bürgerstiftung Kassel, Stiftung Bildung.",
    "a2.h": "Wettbewerb",
    "a2.p": "Offener Wettbewerb mit Frist. Ferry-Porsche-Challenge, Ravensburger Klasse-Wettbewerb.",
    "a3.h": "Anfrage",
    "a3.p": "Erst ein Gespräch, dann ein Antrag. Sparkassenstiftungen, Landesstiftung Miteinander in Hessen.",
    "a4.h": "Eingeladen",
    "a4.p": "Nur eingeladene Projekte. Der Weg führt über Menschen, die schon drin sind.",
    "a5.h": "Operativ",
    "a5.p": "Die Stiftung arbeitet mit eigenen Programmen. Andocken heißt hier: mitarbeiten.",
    "a6.h": "Kooperation",
    "a6.p": "Nur über gemeinsame Programme, etwa mit Ministerien oder Verbänden.",
    "a7.h": "Träger-Partnerschaft",
    "a7.p": "Förderung über Mitgliedschaft oder Trägerschaft. Kolping, Diakonie, Paritätischer, Kammern.",
    "a8.h": "Boden",
    "a8.p": "Kein Geld, sondern Grund und Boden: gekauft und dauerhaft verpachtet. Edith Maryon Stiftung.",
    "m.kicker": "Zusammenfinden",
    "m.h2": "So finden Projekte, Stiftungen und Menschen zueinander.",
    "m1.h": "Tags wählen",
    "m1.p": "Ein Projekt wählt drei bis sechs Themen aus einem gemeinsamen Vokabular, dazu Region und Andock-Feld. Eine Stiftung trägt ihre Themen, Rechtsform, Region und ihren Antragsweg ein.",
    "m2.h": "Gemeinsames zählen",
    "m2.p": "Wir zählen die gemeinsamen Themen und prüfen Region, Größenordnung, Antragsweg und Frist. Aus 280 Stiftungen wird so deine Liste, und jede Zeile zeigt, warum sie dort steht.",
    "m3.h": "Auf der Karte sehen",
    "m3.p": "Die Pin-Farbe zeigt den Antragsweg, die Größe das Fördervolumen. Filtern kannst du nach Förderkriterium, Region und Antragsweg. Fehlt eine Stiftung, trag sie nach.",
    "cl.h2": "Bring dein Projekt auf die Karte.",
    "cl.p": "Oder finde als Stiftung, was zu deinem Zweck passt. Oder gib dazu. Zwei Minuten, keine E-Mail-Anmeldung, deine Identität bleibt auf deinem Gerät.",
    "cl.link": "Karte ansehen",
    "cl.android": "Android-App herunterladen",
    "ft.about": "Anstifter, Zustifter, Stiftungen und Projekte auf einer Karte. Getragen vom Kollektiv Lichtung e.V.",
    "ft.raum": "Der Raum",
    "ft.erfahren": "Erfahren",
    "ft.fuerwen": "Für wen",
    "ft.impressum": "Impressum",
    "ft.datenschutz": "Datenschutz",
    "ft.bottom": "Freie Software, offene Daten, deine Identität bei dir.",
    "kp.kicker": "Der Kreislauf",
    "kp.h1": "So läuft es.",
    "kp.lede": "Vier Rollen, sechs Wege, das Vertrauen in der Mitte. Kein Antrag, der in einer Schublade landet. Jede Gabe bleibt sichtbar und löst die nächste aus.",
    "kp.s1.h": "Anstifter fangen an",
    "kp.s1.p": "Anstifter sind Menschen. Sie starten Projekte, bringen ihre Begabung ein und arbeiten in Stiftungen mit. Von ihnen kommt der erste Anstoß.",
    "kp.s2.h": "Zustifter geben dazu",
    "kp.s2.p": "Wer Wirkung sieht, gibt dazu: in eine Stiftung oder direkt an ein Projekt. Beide Wege stehen offen, beide bleiben sichtbar.",
    "kp.s3.h": "Stiftungen fördern",
    "kp.s3.p": "Die Stiftung findet über die Tags, was zu ihrem Zweck passt, und fördert. Dafür bekommt sie einen eigenen Raum: Karte, Community, Quests.",
    "kp.s4.h": "Projekte arbeiten draußen",
    "kp.s4.p": "Projekte entstehen an einem Ort, mit Menschen, die sich in die Augen sehen. Sie nehmen Gaben aus allen drei Richtungen an.",
    "kp.s5.h": "Die Wirkung kommt zurück",
    "kp.s5.p": "Was aus einer Gabe wurde, bleibt auf der Karte. Anstifter, Zustifter und Stiftungen sehen es und geben weiter. So schließt sich der Kreis.",
    "kp.mitte.h": "Was in der Mitte steht",
    "kp.mitte.p": "Vier Schichten tragen das Ganze: innen das Vertrauen, außen das Werkzeug. Ohne sie wäre der Kreis nur ein Bild.",
    "kp.cta.h2": "Leg los.",
    "kp.cta.p": "Als Anstifter, Zustifter, Stiftung oder Projekt. Der erste Schritt ist ein Pin auf der Karte.",
    "kp.cta.link": "Zurück zur Übersicht",
    "nav.anstifter": "Anstifter",
    "nav.anstifter.s": "Starte ein Projekt, bring deine Begabung ein, arbeite in einer Stiftung mit.",
    "nav.zustifter": "Zustifter",
    "nav.zustifter.s": "Gib in eine Stiftung oder direkt an ein Projekt.",
    "kp.m1.h": "Vertrauen",
    "kp.m1.p": "Das Real Life Trust Protokoll. Zwei Menschen treffen sich und bestätigen das gegenseitig. Daraus wächst das Netz. Deine Identität liegt auf deinem Gerät, nicht auf unserem Server.",
    "kp.m2.h": "Profile",
    "kp.m2.p": "Menschen, Projekte und Stiftungen zeigen, wer sie sind und was sie brauchen. Das Profil gehört dir und wandert mit, wenn du den Anbieter wechselst.",
    "kp.m3.h": "Karte",
    "kp.m3.p": "Hier treffen sich alle vier Rollen. Aus einem Eintrag wird ein Ort, den du besuchen kannst.",
    "kp.m4.h": "Stack",
    "kp.m4.p": "Der Real Life Stack ist der Werkzeugkasten: Karte, Kalender, Kanban, Feed. Jede Gemeinschaft stellt sich zusammen, was sie braucht. Offener Quellcode, selbst hostbar."
  },
  "en": {
    "meta.title": "trustdonation — Projects find foundations. Foundations find impact.",
    "meta.desc": "Initiators, co-donors, foundations and projects on one map. Every project shows what it needs. Every foundation finds what fits its purpose. Every gift becomes visible.",
    "meta.title.kreislauf": "trustdonation — The cycle",
    "meta.desc.kreislauf": "How it flows: initiators found and start, co-donors give, foundations fund, projects show themselves and show impact. Everything interlocks.",
    "aria.schema": "Light or dark",
    "aria.menue": "Open or close menu",
    "nav.fuerwen": "For whom",
    "nav.projekte": "Projects",
    "nav.projekte.s": "Show your project on the map and find the foundations that fit you.",
    "nav.stiftungen": "Foundations",
    "nav.stiftungen.s": "Find projects for your purpose and get your own space.",
    "nav.kreislauf": "The cycle",
    "nav.ressourcen": "Resources",
    "nav.raum": "The space",
    "nav.karte": "Map",
    "nav.karte.s": "All foundations and projects on one map, right in the app.",
    "nav.rubriken": "Funding criteria",
    "nav.rubriken.s": "The eleven fields foundations fund in.",
    "nav.antragswege": "Application paths",
    "nav.antragswege.s": "Open, competition, request, partnership, land.",
    "nav.matching": "How it comes together",
    "nav.matching.s": "Projects, foundations and people meet through topics, region and path.",
    "nav.offen": "Open",
    "nav.quellcode": "Real Life Stack",
    "nav.quellcode.s": "The open source code on GitHub.",
    "nav.instanz": "Your own instance",
    "nav.instanz.s": "Configuration instead of a fork.",
    "nav.android": "Android app",
    "nav.android.s": "APK, 6 MB, straight to your phone.",
    "nav.ueber": "Real Life Network",
    "nav.ueber.s": "The network behind trustdonation.",
    "nav.mitmachen": "Join in",
    "nav.sprache": "Language",
    "nav.stil": "Language style",
    "nav.stil.hinweis": "Language styles exist in German for now.",
    "nav.mehr": "More",
    "nav.app": "Open app",
    "cta.app": "Open app →",
    "hero.eyebrow": "Initiators, co-donors, foundations and projects on one map",
    "hero.h1": "Projects find foundations. Foundations find impact.",
    "hero.lede": "trustdonation brings initiators, co-donors, foundations and projects onto one map. Every project shows what it needs. Every foundation finds what fits its purpose. Every gift becomes visible where it works: outside, in real life.",
    "hero.link": "See the cycle",
    "hero.note": "Carried by Kollektiv Lichtung e.V. Your identity stays on your device, not with us.",
    "frame.open": "Open the map in the app →",
    "frame.stiftungen": "Foundations",
    "frame.projekte": "Projects",
    "proof": "<strong>280 German foundations</strong> reviewed and sorted into eleven funding criteria.",
    "r.kicker": "For whom",
    "r.h2": "Four roles, one weave.",
    "r.lede": "Initiators are people: they found projects, carry them with their gifts and grow into foundations. Co-donors give to foundations and to projects. Foundations fund. Projects work outside.",
    "ra.verb": "Initiate",
    "ra.h3": "Initiators: set things in motion.",
    "ra.p": "Initiators are people. They found projects, carry them with their gifts and grow into foundations, as the next generation working there. Time, knowledge, tools, space: the first push comes from them.",
    "ra.link": "Initiate →",
    "ra.a": "Workshop at the station",
    "ra.as": "Three people, one room, a beginning",
    "ra.at": "founded",
    "ra.b": "Jonas brings his welder",
    "ra.bs": "Workshop at the station",
    "ra.bt": "Gift",
    "ra.c": "Lena on the foundation board",
    "ra.cs": "Buergerstiftung Kassel, for two years",
    "ra.ct": "Next generation",
    "ra.note": "Every encounter is an entry in the Web of Trust, confirmed by both sides.",
    "rz.verb": "Co-donate",
    "rz.h3": "Co-donors: give where you see the impact.",
    "rz.p": "You give to an existing foundation or fund a project directly. Every gift stays visible: who gave it, where it went, what came of it. Trust grows from what can be seen.",
    "rz.link": "Co-donate →",
    "rz.a": "Endowment gift",
    "rz.as": "Education foundation · Crafts fund",
    "rz.at": "5,000 EUR",
    "rz.b": "Direct funding",
    "rz.bs": "Model school Gudensberg · Grounds",
    "rz.bt": "visible",
    "rz.c": "Anna gives every month",
    "rz.cs": "Workshop at the station, 50 EUR",
    "rz.ct": "regular",
    "rz.note": "Every gift is an entry in the Web of Trust, confirmed by both sides.",
    "rs.verb": "Find",
    "rs.h3": "Foundations: find projects that carry your purpose.",
    "rs.p": "Your funding purpose as tags, your application path, your region. The map shows who is already at work. For your purpose we build your own space: map, community, quests. You watch your community grow and carry the whole at the same time.",
    "rs.link": "Register a foundation →",
    "rs.a": "Community foundation Kassel",
    "rs.as": "open · up to 5,000 EUR · online form",
    "rs.at": "open",
    "rs.b": "Software AG Foundation, Darmstadt",
    "rs.bs": "two stages · 20,000 to 500,000 EUR",
    "rs.bt": "two-stage",
    "rs.c": "Edith Maryon Foundation, Basel",
    "rs.cs": "buys land, leases it permanently",
    "rs.ct": "Land",
    "rs.note": "Every entry shows its source and check date. Foundations keep their own profile.",
    "rp.verb": "Show",
    "rp.h3": "Projects: show what grows outside.",
    "rp.p": "Projects happen in real life, outside, where you can touch them, with people in one place. A pin on the map, three to six topics, a region. Your tags produce the list of foundations that match your topics.",
    "rp.link": "Create a project →",
    "rp.a": "Workshop at the station",
    "rp.as": "#crafts #youth #hesse",
    "rp.at": "4 fit",
    "rp.b": "Model school Gudensberg",
    "rp.bs": "#education #potential #reform-pedagogy",
    "rp.bt": "9 fit",
    "rp.c": "Full moon fire Lohre",
    "rp.cs": "#community #peace #inner-work",
    "rp.ct": "3 fit",
    "rp.note": "Sorted by shared topics, region and size. Every line shows why.",
    "k.kicker": "The cycle",
    "k.h2": "A cycle, not an application.",
    "k.lede": "In the middle stands trust: the Real Life Trust Protocol, around it profiles, map and stack. Outside, the four roles. Initiators found and carry, co-donors give, foundations fund, projects work outside. And the impact returns to everyone.",
    "d.kern": "Trust",
    "d.kern.sub": "Trust Protocol",
    "d.profile": "Profiles",
    "d.karte": "Map",
    "d.stack": "Stack",
    "d.anstifter": "Initiators",
    "d.anstifter.sub": "People",
    "d.zustifter": "Co-donors",
    "d.zustifter.sub": "Gifts",
    "d.stiftungen": "Foundations",
    "d.stiftungen.sub": "Capital",
    "d.projekte": "Projects",
    "d.projekte.sub": "in real life",
    "d.l1": "grow into",
    "d.l2": "found, carry",
    "d.l3": "give to",
    "d.l4": "fund directly",
    "d.l5": "fund",
    "d.l6": "impact returns",
    "k.link": "See the whole cycle →",
    "band.big": "One pot,<br><em>many spaces.</em>",
    "band.p": "For every foundation we build its space: map, community, quests. All foundations pay into one shared pot that carries the base, the development and the association. Each one watches its own community grow and carries the whole at the same time.",
    "fact1": "foundations reviewed",
    "fact2": "application paths",
    "fact3": "funding criteria",
    "ru.kicker": "Funding criteria",
    "ru.h2": "Eleven fields in which funding happens.",
    "ru.lede": "Every project and every foundation places itself here. Matching emerges from the overlap.",
    "ru1": "Social innovation and common good",
    "ru2": "Digital sovereignty and open source",
    "ru3": "Civic education and democracy",
    "ru4": "Culture and art",
    "ru5": "Crafts and vocational orientation",
    "ru6": "Children, youth and family",
    "ru7": "Health and prevention",
    "ru8": "Rural development and region",
    "ru9": "Sustainability and circular economy",
    "ru10": "Peace and understanding",
    "ru11": "Education and free learning spaces",
    "a.kicker": "Resources",
    "a.h2": "What foundations bring, and how to dock on.",
    "a.lede": "Foundations bring purpose, capital, network and knowledge. The way to them is rarely the same. Eight application paths we distinguish on the map.",
    "a1.h": "Open",
    "a1.p": "Openly advertised, any organisation can apply. Community foundation Kassel, Stiftung Bildung.",
    "a2.h": "Competition",
    "a2.p": "Open competition with a deadline. Ferry Porsche Challenge, Ravensburger class competition.",
    "a3.h": "Request",
    "a3.p": "Informal, a conversation first. Savings bank foundations, state foundation Miteinander in Hessen.",
    "a4.h": "Invited",
    "a4.p": "Invited projects only. The way leads through people who are already inside.",
    "a5.h": "Operative",
    "a5.p": "The foundation runs its own programmes. Docking on means: working along.",
    "a6.h": "Cooperation",
    "a6.p": "Only through joint programmes, for instance with ministries or associations.",
    "a7.h": "Partnership",
    "a7.p": "Funding through membership or sponsorship. Kolping, Diakonie, Paritätischer, chambers.",
    "a8.h": "Land",
    "a8.p": "No cash but land: bought and leased permanently. Edith Maryon Foundation.",
    "m.kicker": "Coming together",
    "m.h2": "How projects, foundations and people find each other.",
    "m1.h": "Choose tags",
    "m1.p": "A project carries three to six topics from a shared vocabulary, one region and one docking field. A foundation carries its topics, legal form, region and application path.",
    "m2.h": "Count what is shared",
    "m2.p": "We count the shared topics and check region, size, application path and deadline. That makes a list, and every line shows why it is there.",
    "m3.h": "See it on the map",
    "m3.p": "Pin colour shows the application path, size shows the funding volume. Filter by criterion, region and path. If a foundation is missing, add it.",
    "cl.h2": "Bring your project onto the map.",
    "cl.p": "Or find, as a foundation, what fits your purpose. Or initiate, or co-donate. Two minutes, your identity stays with you. The rest grows in the weave.",
    "cl.link": "View the map",
    "cl.android": "Download Android app",
    "ft.about": "Initiators, co-donors, foundations and projects on one map. Carried by Kollektiv Lichtung e.V.",
    "ft.raum": "The space",
    "ft.erfahren": "Learn",
    "ft.fuerwen": "For whom",
    "ft.impressum": "Imprint",
    "ft.datenschutz": "Privacy",
    "ft.bottom": "Free software, open data, your identity with you.",
    "kp.kicker": "The cycle",
    "kp.h1": "This is how it flows.",
    "kp.lede": "Four roles, six movements, trust in the middle. No application that lands in a drawer, but a weave in which every gift stays visible and triggers the next.",
    "kp.s1.h": "Initiators initiate",
    "kp.s1.p": "Initiators are people. They found projects, bring in their gifts and grow into foundations, working there. The first push.",
    "kp.s2.h": "Co-donors give",
    "kp.s2.p": "Whoever sees impact adds to it: to a foundation or directly to a project. Both paths are open, both stay visible.",
    "kp.s3.h": "Foundations fund",
    "kp.s3.p": "The foundation finds via tags what fits its purpose, and funds. Each foundation gets its own space: map, community, quests.",
    "kp.s4.h": "Projects work outside",
    "kp.s4.p": "Projects happen in real life, in one place, with people who look each other in the eye. They accept gifts from all three directions.",
    "kp.s5.h": "Impact returns",
    "kp.s5.p": "What came of a gift stays on the map. Initiators, co-donors and foundations see it and pass it on. So the circle closes.",
    "kp.mitte.h": "What stands in the middle",
    "kp.mitte.p": "Four layers carry the whole. Trust inside, the tool outside. Without them the circle would be just a picture.",
    "kp.cta.h2": "Step into the circle.",
    "kp.cta.p": "As an initiator, a co-donor, a foundation, a project. The first step is a pin on the map.",
    "kp.cta.link": "Back to the overview",
    "nav.anstifter": "Initiators",
    "nav.anstifter.s": "Found a foundation, start a project, bring people together.",
    "nav.zustifter": "Co-donors",
    "nav.zustifter.s": "Give to a foundation or fund a project directly.",
    "kp.m1.h": "Trust",
    "kp.m1.p": "The Real Life Trust Protocol. Every connection rests on an encounter, every recognition on a deed. Identity stays with the person.",
    "kp.m2.h": "Profiles",
    "kp.m2.p": "People, projects and foundations show who they are and what they need. The profile belongs to whoever keeps it, and travels with them.",
    "kp.m3.h": "Map",
    "kp.m3.p": "Visibility. Here all four roles meet, here an entry becomes a place you can visit.",
    "kp.m4.h": "Stack",
    "kp.m4.p": "The Real Life Stack, the toolbox. Map, calendar, kanban, feed: every community assembles what it needs. Open source."
  },
  "es": {
    "meta.title": "trustdonation — Los proyectos encuentran fundaciones. Las fundaciones encuentran impacto.",
    "meta.desc": "Iniciadores, codonantes, fundaciones y proyectos en un mapa. Cada proyecto muestra lo que necesita. Cada fundación encuentra lo que encaja con su fin. Cada donación se hace visible.",
    "meta.title.kreislauf": "trustdonation — El ciclo",
    "meta.desc.kreislauf": "Así fluye: los iniciadores fundan e inician, los codonantes aportan, las fundaciones financian, los proyectos se muestran y muestran su efecto. Todo se entrelaza.",
    "aria.schema": "Claro u oscuro",
    "aria.menue": "Abrir o cerrar el menú",
    "nav.fuerwen": "Para quién",
    "nav.projekte": "Proyectos",
    "nav.projekte.s": "Muestra tu proyecto en el mapa y encuentra las fundaciones que encajan contigo.",
    "nav.stiftungen": "Fundaciones",
    "nav.stiftungen.s": "Encuentra proyectos para tu fin y recibe tu propio espacio.",
    "nav.kreislauf": "El ciclo",
    "nav.ressourcen": "Recursos",
    "nav.raum": "El espacio",
    "nav.karte": "Mapa",
    "nav.karte.s": "Todas las fundaciones y proyectos en un mapa, directamente en la app.",
    "nav.rubriken": "Criterios de apoyo",
    "nav.rubriken.s": "Los once campos en los que apoyan las fundaciones.",
    "nav.antragswege": "Vías de solicitud",
    "nav.antragswege.s": "Abierta, concurso, consulta, alianza, terreno.",
    "nav.matching": "Cómo todo se encuentra",
    "nav.matching.s": "Proyectos, fundaciones y personas se encuentran por temas, región y vía.",
    "nav.offen": "Abierto",
    "nav.quellcode": "Real Life Stack",
    "nav.quellcode.s": "El código abierto en GitHub.",
    "nav.instanz": "Instancia propia",
    "nav.instanz.s": "Configuración en vez de fork.",
    "nav.android": "App Android",
    "nav.android.s": "APK, 6 MB, directo al teléfono.",
    "nav.ueber": "Real Life Network",
    "nav.ueber.s": "La red detrás de trustdonation.",
    "nav.mitmachen": "Participar",
    "nav.sprache": "Idioma",
    "nav.stil": "Estilo de lenguaje",
    "nav.stil.hinweis": "Por ahora, los estilos existen en alemán.",
    "nav.mehr": "Más",
    "nav.app": "Abrir app",
    "cta.app": "Abrir app →",
    "hero.eyebrow": "Iniciadores, codonantes, fundaciones y proyectos en un mapa",
    "hero.h1": "Los proyectos encuentran fundaciones. Las fundaciones encuentran impacto.",
    "hero.lede": "trustdonation reúne en un mapa a iniciadores, codonantes, fundaciones y proyectos. Cada proyecto muestra lo que necesita. Cada fundación encuentra lo que encaja con su fin. Cada donación se hace visible donde actúa: fuera, en la vida real.",
    "hero.link": "Ver el ciclo",
    "hero.note": "Sostenido por Kollektiv Lichtung e.V. Tu identidad queda en tu dispositivo, no con nosotros.",
    "frame.open": "Abrir el mapa en la app →",
    "frame.stiftungen": "Fundaciones",
    "frame.projekte": "Proyectos",
    "proof": "<strong>280 fundaciones alemanas</strong> revisadas y ordenadas en once criterios de apoyo.",
    "r.kicker": "Para quién",
    "r.h2": "Cuatro roles, un tejido.",
    "r.lede": "Los iniciadores son personas: fundan proyectos, los sostienen con sus dones y crecen dentro de las fundaciones. Los codonantes aportan a fundaciones y a proyectos. Las fundaciones financian. Los proyectos actúan fuera.",
    "ra.verb": "Iniciar",
    "ra.h3": "Iniciadores: pon algo en marcha.",
    "ra.p": "Los iniciadores son personas. Fundan proyectos, los sostienen con sus dones y crecen dentro de las fundaciones, como el relevo que allí colabora. Tiempo, saber, herramientas, espacio: el primer impulso viene de ellos.",
    "ra.link": "Iniciar →",
    "ra.a": "Taller en la estación",
    "ra.as": "Tres personas, una sala, un comienzo",
    "ra.at": "fundado",
    "ra.b": "Jonas trae su equipo de soldar",
    "ra.bs": "Taller en la estación",
    "ra.bt": "Don",
    "ra.c": "Lena en el patronato",
    "ra.cs": "Buergerstiftung Kassel, desde hace dos años",
    "ra.ct": "Relevo",
    "ra.note": "Cada encuentro es una entrada en el Web of Trust, confirmada por ambas partes.",
    "rz.verb": "Codonar",
    "rz.h3": "Codonantes: da donde ves el efecto.",
    "rz.p": "Aportas a una fundación existente o financias un proyecto directamente. Cada donación sigue visible: quién la dio, adónde fue, qué salió de ella. La confianza crece de lo que se puede ver.",
    "rz.link": "Codonar →",
    "rz.a": "Aportación",
    "rz.as": "Fundación Educación · Fondo Artesanía",
    "rz.at": "5.000 EUR",
    "rz.b": "Financiación directa",
    "rz.bs": "Escuela modelo Gudensberg · Terreno",
    "rz.bt": "visible",
    "rz.c": "Anna aporta cada mes",
    "rz.cs": "Taller en la estación, 50 EUR",
    "rz.ct": "periódico",
    "rz.note": "Cada donación es una entrada en el Web of Trust, confirmada por ambas partes.",
    "rs.verb": "Encontrar",
    "rs.h3": "Fundaciones: encuentra proyectos que sostengan tu fin.",
    "rs.p": "Tu fin fundacional como etiquetas, tu vía de solicitud, tu región. El mapa muestra quién ya trabaja. Para tu fin construimos tu propio espacio: mapa, comunidad, misiones. Ves crecer tu comunidad y a la vez sostienes el conjunto.",
    "rs.link": "Registrar una fundación →",
    "rs.a": "Fundación ciudadana de Kassel",
    "rs.as": "abierta · hasta 5.000 EUR · formulario en línea",
    "rs.at": "abierta",
    "rs.b": "Fundación Software AG, Darmstadt",
    "rs.bs": "dos fases · de 20.000 a 500.000 EUR",
    "rs.bt": "en dos pasos",
    "rs.c": "Fundación Edith Maryon, Basilea",
    "rs.cs": "compra terreno y lo arrienda de forma permanente",
    "rs.ct": "Suelo",
    "rs.note": "Cada entrada muestra su fuente y su fecha de revisión. Las fundaciones cuidan su propio perfil.",
    "rp.verb": "Mostrar",
    "rp.h3": "Proyectos: muestra lo que nace fuera.",
    "rp.p": "Los proyectos nacen en la vida real, fuera, donde se pueden tocar, con personas en un lugar. Un pin en el mapa, de tres a seis temas, una región. De tus etiquetas sale la lista de fundaciones que coinciden con tus temas.",
    "rp.link": "Crear un proyecto →",
    "rp.a": "Taller en la estación",
    "rp.as": "#artesanía #juventud #hesse",
    "rp.at": "4 encajan",
    "rp.b": "Escuela modelo Gudensberg",
    "rp.bs": "#educación #potencial #pedagogía-reformista",
    "rp.bt": "9 encajan",
    "rp.c": "Hoguera de luna llena Lohre",
    "rp.cs": "#comunidad #paz #trabajo-interior",
    "rp.ct": "3 encajan",
    "rp.note": "Ordenado por temas comunes, región y magnitud. Cada línea muestra por qué.",
    "k.kicker": "El ciclo",
    "k.h2": "Un ciclo, no una solicitud.",
    "k.lede": "En el centro está la confianza: el Real Life Trust Protocol, y alrededor los perfiles, el mapa y el stack. Fuera, los cuatro roles. Los iniciadores fundan y sostienen, los codonantes aportan, las fundaciones financian, los proyectos actúan fuera. Y el efecto vuelve a todos.",
    "d.kern": "Confianza",
    "d.kern.sub": "Trust Protocol",
    "d.profile": "Perfiles",
    "d.karte": "Mapa",
    "d.stack": "Stack",
    "d.anstifter": "Iniciadores",
    "d.anstifter.sub": "Personas",
    "d.zustifter": "Codonantes",
    "d.zustifter.sub": "Donaciones",
    "d.stiftungen": "Fundaciones",
    "d.stiftungen.sub": "Capital",
    "d.projekte": "Proyectos",
    "d.projekte.sub": "en la vida real",
    "d.l1": "crecen dentro",
    "d.l2": "fundan, sostienen",
    "d.l3": "aportan",
    "d.l4": "financian directo",
    "d.l5": "financian",
    "d.l6": "el efecto vuelve",
    "k.link": "Ver el ciclo completo →",
    "band.big": "Un fondo,<br><em>muchos espacios.</em>",
    "band.p": "Para cada fundación construimos su espacio: mapa, comunidad, misiones. Todas las fundaciones aportan a un fondo común que sostiene la base, el desarrollo y la asociación. Cada una ve crecer su propia comunidad y a la vez sostiene el conjunto.",
    "fact1": "fundaciones revisadas",
    "fact2": "vías de solicitud",
    "fact3": "criterios de apoyo",
    "ru.kicker": "Criterios de apoyo",
    "ru.h2": "Once campos en los que se financia.",
    "ru.lede": "Cada proyecto y cada fundación se sitúa aquí. Del solapamiento nace el matching.",
    "ru1": "Innovación social y bien común",
    "ru2": "Soberanía digital y código abierto",
    "ru3": "Educación cívica y democracia",
    "ru4": "Cultura y arte",
    "ru5": "Artesanía y orientación profesional",
    "ru6": "Infancia, juventud y familia",
    "ru7": "Salud y prevención",
    "ru8": "Desarrollo rural y región",
    "ru9": "Sostenibilidad y economía circular",
    "ru10": "Paz y entendimiento",
    "ru11": "Educación y espacios libres de aprendizaje",
    "a.kicker": "Recursos",
    "a.h2": "Lo que aportan las fundaciones, y cómo acercarse.",
    "a.lede": "Las fundaciones aportan fin, capital, red y saber. El camino hacia ellas rara vez es el mismo. Ocho vías de solicitud que distinguimos en el mapa.",
    "a1.h": "Abierta",
    "a1.p": "Convocatoria abierta, cualquier entidad puede solicitar. Fundación ciudadana de Kassel, Stiftung Bildung.",
    "a2.h": "Concurso",
    "a2.p": "Concurso abierto con plazo. Ferry Porsche Challenge, concurso escolar Ravensburger.",
    "a3.h": "Consulta",
    "a3.p": "Informal, primero una conversación. Fundaciones de cajas de ahorros, fundación estatal Miteinander in Hessen.",
    "a4.h": "Por invitación",
    "a4.p": "Solo proyectos invitados. El camino pasa por personas que ya están dentro.",
    "a5.h": "Operativa",
    "a5.p": "La fundación trabaja con programas propios. Acercarse significa colaborar.",
    "a6.h": "Cooperación",
    "a6.p": "Solo a través de programas conjuntos, por ejemplo con ministerios o asociaciones.",
    "a7.h": "Alianza de entidades",
    "a7.p": "Apoyo mediante membresía o titularidad. Kolping, Diakonie, Paritätischer, cámaras.",
    "a8.h": "Terreno",
    "a8.p": "Sin dinero en efectivo, sino terreno: comprado y arrendado de forma permanente. Fundación Edith Maryon.",
    "m.kicker": "Encontrarse",
    "m.h2": "Así se encuentran proyectos, fundaciones y personas.",
    "m1.h": "Elegir etiquetas",
    "m1.p": "Un proyecto lleva de tres a seis temas de un vocabulario común, una región y un campo de anclaje. Una fundación lleva sus temas, su forma jurídica, su región y su vía de solicitud.",
    "m2.h": "Contar lo común",
    "m2.p": "Contamos los temas comunes y revisamos región, magnitud, vía de solicitud y plazo. De ahí sale una lista, y cada línea muestra por qué está ahí.",
    "m3.h": "Verlo en el mapa",
    "m3.p": "El color del pin muestra la vía de solicitud, el tamaño el volumen de apoyo. Filtra por criterio, región y vía. Si falta una fundación, añádela.",
    "cl.h2": "Lleva tu proyecto al mapa.",
    "cl.p": "O encuentra, como fundación, lo que encaja con tu fin. O inicia, o codona. Dos minutos, tu identidad queda contigo. El resto crece en el tejido.",
    "cl.link": "Ver el mapa",
    "cl.android": "Descargar app Android",
    "ft.about": "Iniciadores, codonantes, fundaciones y proyectos en un solo mapa. Sostenido por Kollektiv Lichtung e.V.",
    "ft.raum": "El espacio",
    "ft.erfahren": "Conocer",
    "ft.fuerwen": "Para quién",
    "ft.impressum": "Aviso legal",
    "ft.datenschutz": "Privacidad",
    "ft.bottom": "Software libre, datos abiertos, tu identidad contigo.",
    "kp.kicker": "El ciclo",
    "kp.h1": "Así fluye.",
    "kp.lede": "Cuatro roles, seis movimientos, la confianza en el centro. Ninguna solicitud que acabe en un cajón, sino un tejido en el que cada donación sigue visible y desencadena la siguiente.",
    "kp.s1.h": "Los iniciadores inician",
    "kp.s1.p": "Los iniciadores son personas. Fundan proyectos, aportan sus dones y crecen dentro de las fundaciones, donde colaboran. El primer impulso.",
    "kp.s2.h": "Los codonantes aportan",
    "kp.s2.p": "Quien ve el efecto, añade: a una fundación o directamente a un proyecto. Ambos caminos están abiertos, ambos siguen visibles.",
    "kp.s3.h": "Las fundaciones financian",
    "kp.s3.p": "La fundación encuentra por las etiquetas lo que encaja con su fin, y financia. Cada fundación recibe su propio espacio: mapa, comunidad, misiones.",
    "kp.s4.h": "Los proyectos actúan fuera",
    "kp.s4.p": "Los proyectos nacen en la vida real, en un lugar, con personas que se miran a los ojos. Reciben donaciones de las tres direcciones.",
    "kp.s5.h": "El efecto vuelve",
    "kp.s5.p": "Lo que salió de una donación queda en el mapa. Iniciadores, codonantes y fundaciones lo ven y siguen dando. Así se cierra el círculo.",
    "kp.mitte.h": "Lo que está en el centro",
    "kp.mitte.p": "Cuatro capas sostienen el conjunto. Dentro la confianza, fuera la herramienta. Sin ellas el círculo sería solo una imagen.",
    "kp.cta.h2": "Entra en el círculo.",
    "kp.cta.p": "Como iniciador, como codonante, como fundación, como proyecto. El primer paso es un pin en el mapa.",
    "kp.cta.link": "Volver a la vista general",
    "nav.anstifter": "Iniciadores",
    "nav.anstifter.s": "Funda una fundación, inicia un proyecto, reúne personas.",
    "nav.zustifter": "Codonantes",
    "nav.zustifter.s": "Aporta a una fundación o financia un proyecto directamente.",
    "kp.m1.h": "Confianza",
    "kp.m1.p": "El Real Life Trust Protocol. Cada conexión se basa en un encuentro, cada reconocimiento en un hecho. La identidad queda con la persona.",
    "kp.m2.h": "Perfiles",
    "kp.m2.p": "Personas, proyectos y fundaciones muestran quiénes son y qué necesitan. El perfil pertenece a quien lo lleva, y viaja con él.",
    "kp.m3.h": "Mapa",
    "kp.m3.p": "La visibilidad. Aquí se encuentran los cuatro roles, aquí una entrada se vuelve un lugar que se puede visitar.",
    "kp.m4.h": "Stack",
    "kp.m4.p": "El Real Life Stack, la caja de herramientas. Mapa, calendario, kanban, muro: cada comunidad reúne lo que necesita. Código abierto."
  }
}

// Sprachstile: eigene Stimmen fuer den deutschen Text, je eine JSON-Datei unter /stile/.
// "klar" ist der Text in site.js selbst. Ein Stil legt sich ueber T.de, fehlende Schluessel fallen auf T.de zurueck.
var STILE = {
  "klar": "Klartext", "kindgerecht": "Kindgerecht", "tiefstapelei": "Tiefstapelei", "herzens-sprache": "Herzens-Sprache",
  "schamanisch": "Schamanisch", "soziologen-sprech": "Soziologen-Sprech", "groessenwahn": "Größenwahn",
  "kraftvolle-sprache": "Kraftvolle Sprache", "marktschreier": "Marktschreier"
}
var STIL_CACHE = {}
var aktiveSprache = "de", aktiverStil = "klar"

function texteAnwenden(d, l) {
  var els = document.querySelectorAll("[data-t]")
  for (var i = 0; i < els.length; i++) { var k = els[i].dataset.t; if (d[k] != null) els[i].innerHTML = d[k] }
  var ar = document.querySelectorAll("[data-t-aria]")
  for (var j = 0; j < ar.length; j++) { var ka = ar[j].dataset.tAria; if (d[ka] != null) ar[j].setAttribute("aria-label", d[ka]) }
  document.documentElement.lang = l
  var seite = document.body.dataset.seite || ""
  var tk = seite ? "meta.title." + seite : "meta.title", dk = seite ? "meta.desc." + seite : "meta.desc"
  if (d[tk]) document.title = d[tk]
  var m = document.querySelector('meta[name="description"]'); if (m && d[dk]) m.setAttribute("content", d[dk])
}

function auswahlZeigen() {
  var lab = document.getElementById("lang-label")
  if (lab) lab.textContent = aktiveSprache.toUpperCase() + (aktiveSprache === "de" && aktiverStil !== "klar" ? " · " + STILE[aktiverStil] : "")
  var opts = document.querySelectorAll("[data-lang]")
  for (var o = 0; o < opts.length; o++) opts[o].setAttribute("aria-checked", opts[o].dataset.lang === aktiveSprache ? "true" : "false")
  var st = document.querySelectorAll("[data-stil]")
  for (var s = 0; s < st.length; s++) st[s].setAttribute("aria-checked", st[s].dataset.stil === aktiverStil ? "true" : "false")
  document.documentElement.dataset.stile = aktiveSprache === "de" ? "an" : "aus"
}

function anwenden() {
  var d = T[aktiveSprache]
  if (aktiveSprache === "de" && aktiverStil !== "klar") {
    var o = STIL_CACHE[aktiverStil]
    if (!o) { stilLaden(aktiverStil); return }
    var z = {}
    for (var k in T.de) z[k] = T.de[k]
    for (var k2 in o) z[k2] = o[k2]
    d = z
  }
  texteAnwenden(d, aktiveSprache)
  auswahlZeigen()
}

function stilLaden(id) {
  if (!STILE[id] || id === "klar") return
  if (STIL_CACHE[id]) { anwenden(); return }
  fetch("/stile/" + id + ".json", { cache: "no-cache" }).then(function (r) { return r.ok ? r.json() : null }).then(function (o) {
    if (o) { STIL_CACHE[id] = o; if (aktiverStil === id) anwenden() }
    else if (aktiverStil === id) { aktiverStil = "klar"; anwenden() }
  }).catch(function () { if (aktiverStil === id) { aktiverStil = "klar"; anwenden() } })
}

function spracheSetzen(l) {
  if (!T[l]) l = "de"
  aktiveSprache = l
  try { localStorage.setItem("wir-lang", l) } catch (e) {}
  anwenden()
}

// Ein Stil ist immer deutsch: die Wahl schaltet auf Deutsch, wenn noetig.
function stilSetzen(id) {
  if (!STILE[id]) id = "klar"
  aktiverStil = id
  try { localStorage.setItem("wir-stil", id) } catch (e) {}
  if (aktiveSprache !== "de") { spracheSetzen("de"); return }
  anwenden()
}

;(function () {
  var l = null, st = null
  try { l = localStorage.getItem("wir-lang"); st = localStorage.getItem("wir-stil") } catch (e) {}
  if (!l) { var n = (navigator.language || "de").slice(0, 2).toLowerCase(); l = T[n] ? n : "de" }
  aktiveSprache = T[l] ? l : "de"
  aktiverStil = STILE[st] ? st : "klar"
  if (aktiveSprache !== "de" || aktiverStil !== "klar") anwenden(); else auswahlZeigen()
  function schliessen(el) { var m = el.closest(".has-menu"); if (m) { m.dataset.open = "false"; m.querySelector("button").setAttribute("aria-expanded", "false") } }
  var opts = document.querySelectorAll("[data-lang]")
  for (var o = 0; o < opts.length; o++) opts[o].addEventListener("click", function (e) { e.stopPropagation(); spracheSetzen(this.dataset.lang); schliessen(this) })
  var stile = document.querySelectorAll("[data-stil]")
  for (var s = 0; s < stile.length; s++) stile[s].addEventListener("click", function (e) { e.stopPropagation(); stilSetzen(this.dataset.stil); schliessen(this) })
})();

// Aufklapp-Menues: Klick oeffnet und schliesst, Hover laeuft ueber CSS.
;(function () {
  var menues = document.querySelectorAll(".has-menu")
  function alleZu(ausser) {
    for (var i = 0; i < menues.length; i++) if (menues[i] !== ausser) {
      menues[i].dataset.open = "false"
      menues[i].querySelector("button").setAttribute("aria-expanded", "false")
    }
  }
  for (var i = 0; i < menues.length; i++) (function (m) {
    m.querySelector("button").addEventListener("click", function (e) {
      e.stopPropagation()
      var auf = m.dataset.open !== "true"
      alleZu(m); m.dataset.open = auf ? "true" : "false"
      this.setAttribute("aria-expanded", auf ? "true" : "false")
    })
    m.addEventListener("click", function (e) { e.stopPropagation() })
  })(menues[i])
  document.addEventListener("click", function () { alleZu(null) })
  document.addEventListener("keydown", function (e) { if (e.key === "Escape") { alleZu(null); menueSchliessen() } })
})();

function menueUmschalten() {
  var auf = document.body.dataset.menu !== "open"
  document.body.dataset.menu = auf ? "open" : "closed"
  document.querySelector(".burger").setAttribute("aria-expanded", auf ? "true" : "false")
}
function menueSchliessen() {
  document.body.dataset.menu = "closed"
  var b = document.querySelector(".burger"); if (b) b.setAttribute("aria-expanded", "false")
}
function schemaUmschalten() {
  var r = document.documentElement
  var dunkel = r.dataset.theme ? r.dataset.theme === "dark" : matchMedia("(prefers-color-scheme: dark)").matches
  var neu = dunkel ? "light" : "dark"
  r.dataset.theme = neu
  try { localStorage.setItem("rls-theme", neu) } catch (e) {}
}
